name: postgres
channels:
  - conda-forge  
  - defaults
dependencies:
  - postgresql
  - psycopg2
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - sympy
  - numba
  - plotly
  - scikit-learn
  - psutil
  - requests
  - statsmodels
  - pip
  - pip:
    - pandas
    - ipython-sql
    - pydataset
    - tqdm
    - tensorflow
    - coconut
    - openpyxl